flags: {}
extra-package-dbs: []
packages:
- '.'
- '../camfort'
- location: ../fortran-src
  extra-dep: true
- location:
    git: https://github.com/camfort/verifiable-expressions.git
    commit: 738183ae16a3179f0b71165bdaecd2fc17b206cc
  extra-dep: true
extra-deps:
- partial-order-0.1.2.1
- vinyl-0.6.0
- union-0.1.1.2
- GenericPretty-1.2.1
- crackNum-1.9
- syz-0.2.0.0
- FloatingHex-0.4
- sbv-7.3
resolver: lts-9.21